# Generated by Django 5.1.2 on 2024-10-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=20)),
                ('cor_do_cabelo', models.CharField(max_length=30)),
                ('datar_nascimento', models.DateField()),
            ],
        ),
    ]
